ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE products
    MODIFY COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE product_discounts
    MODIFY COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE reservations
    MODIFY COLUMN price DECIMAL(10,2) NULL,
    MODIFY COLUMN reservation_quantity INT NULL,
    MODIFY COLUMN product_id BIGINT NULL;
